---

#matrix:
#  allow_failures:
#    - env: CHECKER="alpine/flake8:3.5.0"
#    - env: CHECKER="alpine/flake8:3.6.0"
#  fast_finish: true

language: bash
sudo: required
services:
  - docker

before_install:
  - docker info
  - docker version

jobs:
  include:

    # Stage of check
    # ==============

    - stage: check
      env:
        CHECKER="alpine/flake8:3.5.0"
      script:
        - docker run --rm -it -v $PWD:/apps/ $CHECKER *.py

    - stage: check
      env:
        CHECKER="alpine/flake8:3.6.0"
      script:
        - docker run --rm -it -v $PWD:/apps/ $CHECKER *.py
